### ISSUE TITLE
Tabula-py missing in yaml

### ISSUE THREAD

**Issue by paul1995tu** [euronion/trace#15]
When using the example scenario from README, `snakemake -jall --restart-times 3 results/default/2030/hvdc-to-elec/ES-DE/results.csv`, it was necessary to include `tabula-py` into the yaml

```
[Wed Jul  6 17:27:32 2022]
rule convert_fraunhofer:
    input: docu/Anhang-Studie-Wege-zu-einem-klimaneutralen-Energiesystem.pdf
    output: inputs/Fraunhofer_ISE_costs.csv, inputs/Fraunhofer_ISE_energy_prices.csv
    jobid: 1
    reason: Missing output files: inputs/Fraunhofer_ISE_energy_prices.csv, inputs/Fraunhofer_ISE_costs.csv
    resources: tmpdir=/tmp, mem=500

Traceback (most recent call last):
  File "/home/pirski/Diplomarbeit/projectz/technology-data/.snakemake/scripts/tmp6e9n3uqg.convert_pdf_fraunhofer_to_dataframe.py", line 14, in <module>
    from tabula import read_pdf
ModuleNotFoundError: No module named 'tabula'
```

**Comment by euronion** [comment]
Should be considered by `snakemake` in the subworkflow. Hm. I'll have a look. Adding the missing package to `tabula-py` is certainly a good workaround.

**Comment by euronion** [comment]
I have removed the complicated inclusion of `technology-data` via parallel manual download from the repository alltogether. Cost data is now directly downloaded from the repository and no additional dependencies should be required anymore (https://github.com/euronion/trace/commit/4c8d67026213764c613a8dad47763c327b265527)
